<?php
// List of Pro checklist rules.
// Add a new rule here with its id, support group, label, and parameters.
return [
    [
        'id'       => 'all_in_one_seo_headline_score',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'all_in_one_seo',
        'label'    => 'All in One SEO Headline Score',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'all_in_one_seo_score',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'all_in_one_seo',
        'label'    => 'All in One SEO Score',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'featured_image_height',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'featured_image',
        'label'    => 'Featured image height',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'featured_image_width',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'featured_image',
        'label'    => 'Featured image width',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'heading_in_hierarchy',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'accessibility',
        'label'    => 'Heading in hierarchy',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'image_count',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'images',
        'label'    => 'Number of images in content',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'approved_by_user',
        'type'     => 'multiple',
        'support'  => 'editor',
        'group'    => 'approval',
        'label'    => 'Approved by user',
    ],
    [
        'id'       => 'no_heading_tags',
        'type'     => 'multiple',
        'support'  => 'editor',
        'group'    => 'content',
        'label'    => 'Avoid heading tags in content',
    ],
    [
        'id'        => 'publish_time_exact',
        'type'      => 'time',
        'support'   => 'editor',
        'group'     => 'publish_date_time',
        'label'     => 'Published at exact time',
        'field_key' => '_publish_time_exact',
    ],
    [
        'id'        => 'publish_time_future',
        'type'      => 'time',
        'support'   => 'editor',
        'group'     => 'publish_date_time',
        'label'     => 'Publish time should be in the future',
        'field_key' => '_publish_time_future'
    ],
    [
        'id'       => 'rank_math_score',
        'type'     => 'counter',
        'support'  => 'editor',
        'group'    => 'rank_math',
        'label'    => 'Rank Math SEO Score',
        'min'      => '',
        'max'      => '',
    ],
    [
        'id'       => 'single_h1_per_page',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'accessibility',
        'label'    => 'Only one H1 tag in content',
    ],
    [
        'id'       => 'table_header',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'accessibility',
        'label'    => 'Tables have a header row',
    ],
    [
        'id'       => 'backorder',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Check the "Allow backorders?" box',
        'post_type' => 'product',
    ],
    [
        'id'       => 'crosssell',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Select some products for "Cross-sells"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'discount',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Discount for the "Sale price"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'downloadable',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Check the "Downloadable" box',
        'post_type' => 'product',
    ],
    [
        'id'       => 'image',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'images',
        'label'    => 'Product image',
        'post_type' => 'product',
    ],
    [
        'id'       => 'manage_stock',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Check the "Manage stock?" box',
        'post_type' => 'product',
    ],
    [
        'id'       => 'regular_price',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Enter a "Regular price"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'sale_price',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Enter a "Sale price"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'sale_price_scheduled',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Schedule the "Sale price"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'sku',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Enter a "SKU"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'sold_individually',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Check the "Sold individually" box',
        'post_type' => 'product',
    ],
    [
        'id'       => 'upsell',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Select some products for "Upsells"',
        'post_type' => 'product',
    ],
    [
        'id'       => 'virtual',
        'type'     => 'simple',
        'support'  => 'editor',
        'group'    => 'woocommerce',
        'label'    => 'Check the "Virtual" box',
        'post_type' => 'product',
    ]
    
];
