path:
  - ./
  - ./core
  - ./modules
jobs: 10
extensions:
  - php
exclude:
  - vendor
  - assets_wp
  - bin
  - build
  - node_modules
  - tests
  - .github
  - assets
  - cache
  - languages
  - .wordpress-org
warning: false
